### ISSUE TITLE
Can roboflow be used to finetune on custom dataset?

### ISSUE THREAD

**Issue by SylviaZiyaZhou** [roboflow/roboflow-100-benchmark#20]

**Comment by mo-traor3-ai** [comment]
Yes, we have tens of thousands of examples of this on Roboflow Universe: https://universe.roboflow.com

You can train with [Roboflow Train credits](https://docs.roboflow.com/train) for [rapid-prototyping](https://blog.roboflow.com/deploy-tab), [model-assisted labeling](https://docs.roboflow.com/annotate/model-assisted-labeling), and even quickly deploy a model to a browser, or edge device, for example.
* https://docs.roboflow.com/inference
* https://docs.roboflow.com/inference-classification
* https://docs.roboflow.com/inference-instance-segmentation
* https://docs.roboflow.com/inference-semantic-segmentation

You also have the option to train a custom model:
* https://models.roboflow.com
* https://github.com/roboflow-ai/notebooks

**Comment by FrancescoSaverioZuppichini** [comment]
Closing, thanks to @mo-traor3-ai
