### ISSUE TITLE
Some small issues with dataset

### ISSUE THREAD

**Issue by 99991** [roboflow/roboflow-100-benchmark#33]
A few images in the `flir-camera-objects/train/` directory contain `:` symbols, so they can not be saved on Windows-related file systems.

There also are a few images which are not 640x640, but the reason could have been that I had to download some classes from the website because the download script did not work. Maybe I chose an incorrect option.

A few samples (width height filename, 22167 total):

```
640 460 acl-x-ray/test/830332-5-pck_17_jpg.rf.070a30237c068c5f13636af0f52251b0.jpg
1920 1080 soda-bottles/test/01_20220317_124928_bmp_jpg.rf.00fb71bebdfe538e9cf72e7316ac14a9.jpg
600 600 rf100/fish-market-ggjso/test/Pabda210_jpg.rf.003688aee4c0c647ae8fa9d75a1012b2.jpg
```

**Comment by yeldarby** [comment]
Thanks for reporting, we will have a look!

**Comment by 99991** [comment]
> should we fix this from the back end or we don't plan to support windows in the new future?

Note that this does not only affect Windows, but also Windows-related file systems like NTFS and exFAT. Chances are that if you try to copy the dataset to a USB flash drive, it will fail because they are often formatted with one of those file systems.

**Comment by FrancescoSaverioZuppichini** [comment]
Closing since this is not linked directly to RF100 but to the backend logic
