### ISSUE TITLE
How to get images in the original aspect ratio?

### ISSUE THREAD

**Issue by sandeepjana** [roboflow/roboflow-100-benchmark#42]
Thanks for your amazing work of creating these datasets. 
The images are appear stretched and squashed to 640x640. I am not sure if I did a mistake in some download options, if any.
IMO, model evaluations must be done on letter box images rather than stretched images for accurate comparison.

**Comment by yeldarby** [comment]
Each dataset has a raw version available in addition to the 640x640 version

![Uploading 7504C367-AEAE-4E4C-AA87-960BBFB145F3.jpeg…]()
