### ISSUE TITLE
Colab notebook error

### ISSUE THREAD

**Issue by joy0010** [roboflow/roboflow-100-benchmark#51]
I followed every step in this video in https://www.youtube.com/watch?v=jIgZMr-PBMo to run the colab code in https://github.com/roboflow/notebooks/blob/main/notebooks/how-to-use-rf100.ipynb.

When I got to this line `!python train.py --img 640 --batch 8 --epochs 100 --name $dataset/results --data $dataset/data.yaml  --weights 'yolov7_training.pt' |& tee $dataset/logs.txt `,  it shows `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`.

Please help me to solve this.

<img width="1467" alt="截屏2023-07-18 18 10 37" src="https://github.com/roboflow/roboflow-100-benchmark/assets/61197663/b9c17339-0eec-4867-8d0d-8243f4e00148">

**Comment by FrancescoSaverioZuppichini** [comment]
I believe the project is dead

**Comment by Jacobsolawetz** [comment]
Hello @joy0010! This is a bug that has been introduced by the YOLOv7 repository.

Please see this fix that the YOLOv7 community has discovered or consider using a different YOLO version

https://github.com/WongKinYiu/yolov7/issues/1101#issuecomment-1314659118
